# Generated by Django 4.2.5 on 2023-09-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('Username', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=8)),
                ('Address', models.CharField(max_length=100)),
                ('PhoneNo', models.IntegerField()),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
