# Generated by Django 4.2.5 on 2023-09-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Name',
        ),
        migrations.AddField(
            model_name='signup',
            name='Email',
            field=models.EmailField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
