# Generated by Django 4.2.5 on 2023-09-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0002_remove_signup_name_signup_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='Profile_Pic',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
