# Generated by Django 4.2.5 on 2023-09-17 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_signup_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Username',
            new_name='Userid',
        ),
        migrations.AddField(
            model_name='signup',
            name='Name',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
    ]
