# Generated by Django 4.2.5 on 2023-09-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_rename_username_signup_userid_signup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('ImgId', models.AutoField(primary_key=True, serialize=False)),
                ('ImgName', models.CharField(max_length=20)),
                ('Images', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
